# Generated by Django 5.1.7 on 2025-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("s_admin", "Super Admin"),
                    ("doctor", "Doctor"),
                    ("receptionist", "Receptionist"),
                    ("room", "Room"),
                ],
                max_length=20,
            ),
        ),
    ]
