# Generated by Django 5.1.7 on 2025-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_consultancy_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Default consultancy fee for this organization",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_session_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2500.0,
                help_text="Default session fee for this organization",
                max_digits=10,
            ),
        ),
    ]
