# Generated by Django 5.1.7 on 2025-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Continue", "Continue"),
                    ("Completed", "Completed"),
                    ("PendingDiscount", "Pending Discount Approval"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
