# Generated by Django 5.1.7 on 2025-05-03 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_consultancy_discount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="consultancy_fee",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="number_of_sessions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="referred_doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Continue", "Continue"),
                    ("ReceptionistReview", "Receptionist Review"),
                    ("Completed", "Completed"),
                    ("PendingDiscount", "Pending Discount Approval"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
