# Generated by Django 5.1.7 on 2025-05-04 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_consultancy_consultancy_fee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="room",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "room"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultancies_as_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "room"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions_as_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_fee",
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10),
        ),
    ]
