# Generated by Django 5.1.7 on 2025-07-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_email"),
        ("appointments", "0007_alter_consultancy_room_alter_session_room_and_more"),
        ("patients", "0002_patient_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Continue", "Continue"),
                    ("ReceptionistReview", "Receptionist Review"),
                    ("Completed", "Completed"),
                    ("PendingDiscount", "Pending Discount Approval"),
                    ("Rejected", "Rejected"),
                    ("SessionEnded", "Session Ended"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("patient", "consultancy", "date_time")},
        ),
        migrations.CreateModel(
            name="RecordLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("consultancy", "Consultancy"),
                            ("session", "Session"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient_name", models.CharField(max_length=255)),
                ("patient_phone", models.CharField(max_length=15)),
                ("patient_gender", models.CharField(max_length=10)),
                ("doctor_name", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "further_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("status", models.CharField(max_length=20)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "feedback_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "number_of_sessions",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                (
                    "consultancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.consultancy",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record Log",
                "verbose_name_plural": "Record Logs",
                "indexes": [
                    models.Index(
                        fields=["date_time"], name="appointment_date_ti_346320_idx"
                    ),
                    models.Index(
                        fields=["record_type"], name="appointment_record__7e9282_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="appointment_organiz_c46da8_idx"
                    ),
                    models.Index(
                        fields=["doctor"], name="appointment_doctor__041031_idx"
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_ce6adc_idx"
                    ),
                ],
            },
        ),
    ]
