# Generated by Django 5.1.7 on 2025-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_alter_consultancy_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancy",
            name="paid_sessions",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
