# Generated by Django 5.1.7 on 2025-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_consultancy_paid_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordlog",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("consultancy", "Consultancy"),
                    ("session", "Session"),
                    ("advance", "Advance"),
                ],
                max_length=20,
            ),
        ),
    ]
